### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by zeleniy** [zeleniy/rDashboard#1]
From requirements:

At the top of the dashboard, there should be a section displaying some user controls like drop down boxes for filtering and toggle buttons (or radio buttons) for slicing and switching between various parameters.

And further:

**TOP LEVEL FILTERS**
This section should have drop down boxes or toggle buttons (radio buttons) for slicing and dicing the data on various parameters. The following parameters can be considered for the main dashboard:

1. Organization [Drop Down]
2. Matter Type [Drop Down]
3. Case Category [Drop Down]
4. Metric [Radio Buttons]
    * Data Volume
    * Item Count
    * Time
5. Location [Drop Down]

**Questions and notices:**

1. There is no `Organization` column in `CaseStatsSummary.xlsx`
2. There is no `Case Category` column in `CaseStatsSummary.xlsx`, but `CaseType` is available. Mistake?
3. There is no `Metric ` column in `CaseStatsSummary.xlsx`

**Comment by rrekapalli** [comment]
1.  You can consider 'Entity Name' as the 'Organization'.  
2. Sorry, this is a mistake.  MatterType is a good filter to consider than the 'CaseType'.
3. I used the word 'Metric' in a generic sense to indicate all 'Count' and 'Size' columns. So, 'DataSourceCount' is ametric and so is 'DataSourceSize'. 

Having said that, please consider these as placeholders for now.  As our application evolves, we may chose to have some other fields as filters. 

Also, whatever filters we apply by clicking on chart elements can be shown as a separate row either above/below the 'Time line brush'.  And there could be a button to clear out all the filters that are applied.

**Comment by zeleniy** [comment]
Filters now can be easily added by config - https://github.com/zeleniy/rDashboard/blob/master/js/main-dashboard.js#L56
