### ISSUE TITLE
Tiles stats calculation

### ISSUE THREAD

**Issue by zeleniy** [zeleniy/rDashboard#2]
**Description:**

a.	**IDENTIFIED** Data Sources Card– This card should display stats related to all identified data sources for all cases (when on case list page) /for a particular case (when on a case details page).  The following details should be on the card:
i.	Count of all data sources that are identified across all matters/cases when on case list page and all data sources for a specific case when on the case details page. (In the above card 48 is the count of all data sources).  The percentage should also be displayed. (In the above card “100% of Total” below the number 48)
ii.	Data Size of all data sources that are identified along with the percentage (in the above card “26.1gb” and “100% of Total”
b.	**COLLECTED** data sources card – This card should display statistics related to all data sources for which “collection” process step is complete. The following details should be on the card.
i.	Count of data sources for which “collection” is complete (consider all end states related to collection completion) along with the completion percentage. (32 Collected 66% in the Orange card above)
ii.	Total size of the data that is successfully collected along with the percentage (e.g. 21.7gb – 83% of Total)
c.	**PROCESSED** data sources card – This should display the statistics related to all data sources for which “PROESSING” phase is complete. The following details should be on the card.
i.	Count of Data Sources for which “PROCESSING” is complete.  Along with the completion percentage. (27 processed 56% on the light blue card above)
ii.	Total size of the data that is successfully processed with the percentage (e.g. 18.7gb – 72% of Total)
d.	**HOSTED** data sources card – This card should display statistics related to all the data sources which have been hosted on the Relativity platform.  The following details should be displayed on the card.
i.	Count of Data Sources which have been successfully hosted. Along with the percentages (calculated on the number of data sources). (15 Hosted – 31% of Total)
ii.	Total size of the data that is successfully hosted. (e.g: 11.2gb – 42% of Total)
e.	**PRODUCED** documents card – This card is slightly different in the sense it does not have any data source level metrics but the counts and sizes related to the productions from Relativity platform. This should display the details about PRODUCTION statistics.  The following are the details:
i.	Count of all documents that are produced. (e.g: 58.1k documents produced)
ii.	Total size of the productions along with the percentage (e.g: 2.3gb – 9% of Total)

**Question:**
Let's start from **IDENTIFIED**. What is data sources - amount of rows in .xlsx file? What is matters/cases? Where data about data sources is stored (which column)?

**Comment by rrekapalli** [comment]
Let me explain a bit about the domain.  The dashboards I am working on is for an application targeting the lawyers and legal industry.  So they have 'Mattes' and 'Cases' as main domain entities.  A matter can have many cases under it.  So a parent-child relation.  

The majority of the workflow is built around 'Cases' in the application. Each case will have 'Custodians' (you can think of custodians as case parties like defendants/plaintiffs etc.).  Each custodian in turn will have multiple 'Data Sources' (you can think of data sources as evidences, like their email, laptop etc.).  

These evidences will have to be 'Identified', 'Collected', 'Processed', 'Hosted', and 'Produced' to the court as an evidence related to that particular case.  Hence, these are the workflow steps.  So, essentially these dashboards should present the stats related to these steps and should be sliced and diced on various other non-workflow related dimensions like 'Matter Type', 'Case Type', and 'Entity Name' etc. for MIS reporting. 

Now, the dataset  I have provided (dummy data) is a summary generated at the case level. So, this will give summary stats for all cases present in our application.  Hope this makes sense!

**Comment by zeleniy** [comment]
Thank you, it's getting more clear. 

So as i can understand now i am working on `all identified data sources for all cases`, but not on `particular case (when on a case details page)` page/dashboard. And it means that `% of Total` should always be equal to 100. Correct?

Also let's do some calculations depending on that very small table - https://github.com/zeleniy/rDashboard/blob/gh-pages/data/CaseStatsSummarySample.tsv. Depending on that data **IDENTIFIED** tile should look like bellow. Correct?

| Left side  | Right side |
| ------------- | ------------- |
| 8Mb | 3 |
| 100% of Total | 100% of Total |

**Comment by rrekapalli** [comment]
Yes.  You are correct.  The dataset includes all cases in the system along with the count of all data sources associated with those cases.  I thought of having a case level filter also applied for these dashboards.  That's why you see references like "when on a case details page" etc.  However for now, we do not want to drill down to a case level for these dashboards.  Hence, the formulas for calculating the percentages would become like this: 

**IDENTIFIED:**
% IDENTIFIED (count)= IdentifiedDataSourcesCount / DataSourceCount
% IDENTIFIED (size)= IdentifiedDataSourcesSize / DataSourcesSize 

**COLLECTED:**
% COLLECTED (count) = CollectionDataSourcesCount / DataSourceCount
% COLLECTED (size) = CollectionDataSourcesSize / DataSourcesSize

PROCESSED:
% PROCESSED (count) = ProcessedVolumesCount / DataSourceCount (Ideally, the denominator should be 'TotalVolumeCount' - which is not part of API currently.)
% PROCESSED (size) = ProcessedVolumesSize/DataSourcesSize (Ideally, the denominator should be 'TotalVolumeSize' - which is not part of the API currently.  Once API is implemented, we'll replace with the accurate denominator)

Similarly, all other stats should be calculated. Please let me know if you have any further questions.

**Comment by zeleniy** [comment]
Thank you. It's getting more clear for me :)

**Comment by rrekapalli** [comment]
Cool!

**Comment by zeleniy** [comment]
I can't get 100%, maybe because data is not complete?
Here is an summary table:

| column name  | column values sum |
| ------------- | ------------- |
| CollectionDataSourcesCount | 214 |
| DataSourceCount | 567 |
| CollectionDataSourcesSize | 1334.7 |
| DataSourceSize | 1418.6 |


```
round(214.0 / 567.0 * 100) = 38%
round(1334.7 / 1418.6 * 100) =  94%
```

@rrekapalli is it correct?

**Comment by rrekapalli** [comment]
Both count and size should not be compared to get 100%.  Both are mutually exclusive.  Each workflow step will have it's own 'Count' percentage as well as it's own Size percentage as they are both different.  We measure each workflow step wise counts and sizes.  Basically, these number can be interpreted as - Out of Total Data Sources available in the system, how many are identified would give us the % IDENTIFIED (count).  Similarly, Out of Total data sources in the system how much data has been identified would give us the % IDENTIFIED (size).  

Similarly, Out of all data sources, how many have been collected would give us the % COLLECTED (count) and out of all the data sources how much data has been collected should give us %COLLECTED (size).

**Comment by rrekapalli** [comment]
This is the reason why we have the top level radio buttons to select which statistic (or metric) to show in individual charts.  When 'Count' is selected, all percentages and all other metrics should display the Counts and should give us the answer to 'How Many'.  Whereas, when we select 'Size' radio button, should give us the answer to 'How Much' data and all the charts should use related statistics (or metrics) accordingly.  

Hope this makes sense.
