### ISSUE TITLE
Charts data

### ISSUE THREAD

**Issue by zeleniy** [zeleniy/rDashboard#3]
<img width="806" alt="screen shot 2017-10-17 at 22 03 00" src="https://user-images.githubusercontent.com/2780617/31684006-33c08abc-b387-11e7-8164-31c58e764b7a.png">

Now every chart shows data defined in first row of `Column Name(s)/ Data Values` column. In case of `Cases By Entity` it is `EntityName`.

`EntityName` column contains data like "Costumes-West", "Costumes-East", "Costumes-North", "Costumes-East", "Costumes-North"...

To show this data i just calculate frequency for each case like:

| Case  | Frequency |
| ------------- | ------------- |
| Costumes-West  | 1 |
| Costumes-East  | 2 |
| Costumes-North  | 2 |

And it is ok. 

`COUNT(CaseID)`
CaseID contains set of unique identificators. Frequency table will contains only 1 for each case. So how to display that data?

`SUM(CollectedDataSourcesSize)` and all other `SUM`s
Every column name within parentheses of `SUM` is set of number. Summary of such set will gain single number. How to display that number in pie or bar chart? It there any sense to do it? Please explain. And how chart should understand that it should to show another statistic? I mean depend on what it should show `EntityName` or `COUNT(CaseID)` or `SUM(CollectedDataSourcesSize)`?

**Comment by rrekapalli** [comment]
I thought of having two separate bar charts for 'CaseType' and 'EntityName', but not based on a selection.  In either case you would need to generate a summary table on the main dataset GROUP BY 'CaseType' or 'Entity Name' columns.  These charts should plot only one metric at a time based on the user selection at the top radio buttons.  When he selects 'Count' radio button, and the 'COLLECTED 'tile has been selected, then the pie chart should plot SUM(CollectedDataSourcesCount) and so on for the other process steps.  Hope this makes sense.  We can have a call to discuss further in case it doesn't makes sense.
