### ISSUE TITLE
Scatterplot

### ISSUE THREAD

**Issue by zeleniy** [zeleniy/rDashboard#4]
<img width="805" alt="screen shot 2017-10-17 at 22 32 15" src="https://user-images.githubusercontent.com/2780617/31685296-1a8b9aec-b38b-11e7-9016-f3c7a6ffdf0d.png">

Scatterplot is 4-dimensional chart. At least in our case. Dimensions are:
* X axis - `CaseName`
* Y axis - `CaseCreatedOn`
* Bubble size - ?
* Color - ?

`CaseName` column contains next data:
```
  [1] "0408Exclusion"           "testing case"            "process001"             
  [4] "test checking"           "42954"                   "FanTest"                
  [7] "MatterTest"              "42955"                   "42956"                  
 [10] "0908Aug"                 "TestCase2"               "42957"                  
```

That is it contains ordinal data. How to plot that data on X axis? I mean it is possible, but anyway could you explain.

**Comment by rrekapalli** [comment]
This chart should plot a circle for each case that exists in the dataset.  The x-axis should be the 'CaseCreatedOn' date value.  The bubble size should correspond to the metric we select at the dashboard level.  For example, if it's 'Count', then the bubble sizes should be based on the 'Datasource Count' of that particular case.  'Color' can be based on the 'CaseType' or 'MatterType' field. Hope this makes sense.

**Comment by zeleniy** [comment]
> The x-axis should be the 'CaseCreatedOn' date value.

> The bubble size should correspond to the metric we select at the dashboard level. For example, if it's 'Count', then the bubble sizes should be based on the 'Datasource Count' of that particular case.

> 'Color' can be based on the 'CaseType' or 'MatterType' field. Hope this makes sense.

@rrekapalli what about y axis?

**Comment by rrekapalli** [comment]
Y-Axis is should be 'Count of Data Sources'.

**Comment by zeleniy** [comment]
I still don't understand. What do you mean under `Count of Data Sources`? `DataSourceCount` and `DataSourceSize` columns?

| dimension | field name |
| ------------- | ------------- |
| x | CaseCreatedOn |
| y | ? (DataSource[Count\|Size]) |
| radius | DataSource[Count\|Size] |
| color | MatterType |

**Comment by rrekapalli** [comment]
No.  Y-Axis should always be DataSource count, and the radius should always be on DataSourceSize. Since we are not implementing the 'Single-Click' event on the case bubbles, keeping them constant should be fine.  However, your suggestions are welcome, if there is any better alternative.

**Comment by zeleniy** [comment]
| dimension | field name |
| ------------- | ------------- |
| x | CaseCreatedOn |
| y | DataSourceCount |
| radius | DataSourceSize |
| color | MatterType |

https://github.com/zeleniy/rDashboard/blob/gh-pages/js/main-dashboard.js#L36-L39

**Comment by zeleniy** [comment]
@rrekapalli in table above i describe chart dimensions. Then in skype you said next:
> But, only for the scatter plot, the bubble radius should change based on Case Count/ Data Sources Size depending on the selected mode.

But DataSourceCount and DataSourceSize already used. So, please, check dimensions correctness and answer what should happen with scatterplot when mode changes from `count` to `size` and from `size` to `count`?

**Comment by rrekapalli** [comment]
I concur with you.  This should be okay as you mentioned above.

dimension | field name
-- | --
x | CaseCreatedOn
y | DataSourceCount
radius | DataSource[Size\|Count]
color | MatterType
