### ISSUE TITLE
Barchart

### ISSUE THREAD

**Issue by zeleniy** [zeleniy/rDashboard#5]
<img width="345" alt="screen shot 2017-10-17 at 22 43 25" src="https://user-images.githubusercontent.com/2780617/31685753-cc11fb16-b38c-11e7-9ca9-7839bb6ea418.png">

Why every bar consist of several rectangles? Where from get data for each rectangle?

**Comment by rrekapalli** [comment]
The idea was to plot 'Case Type' values also shown in the bars and on 'mouseover' event they can show the details belonging to that 'CaseType'.  However, we can just have a single metric plotted as of now.  The bar chart what you currently have on the dashboard should suffice except that the number displayed on the right side should also include the percentage value in parenthesis.

**Comment by zeleniy** [comment]
> include the percentage value in parenthesis

Done
