### ISSUE TITLE
How to reset filters?

### ISSUE THREAD

**Issue by zeleniy** [zeleniy/rDashboard#6]
When you click on slices of pie chart or bar chart every chart receive new data set. It means that to initial data set filter was applied. Some filers may be applied at once for initial data set. How to reset them?

**Comment by rrekapalli** [comment]
Hi Alex, This is a valid question. I have noted a point in the user story under 'Generic Guidelines' section.  I think I forgot a point that each visualization could have title/or a small paragraph highlighting the points that a particular visualization conveys.  We can have a 'Reset' label beside the title or this description with small font.  Upon clicking this 'reset' label would clear out all filters in that particular chart.  

Also, whatever filters we apply by clicking on chart elements can be shown as a separate row either above/below the 'Time line brush'.  And there could be a button to clear out all the filters that are applied on all charts of the dashboard.
