### ISSUE TITLE
Few Generic Comments

### ISSUE THREAD

**Issue by rrekapalli** [zeleniy/rDashboard#7]
1. Tiles at the top:  All tiles should fit into a single row and the font sizes can be reduced to the point where they a clearly visible and at the same time will not overlap/get clipped/ over-flown into the next row. 

2. Can we have three charts in the first row.  Currently, we have only two: Pie-chart based on CaseType  and a Bar Chart on 'EntityName'.  I am thinking of having three charts with widths 25%-50%-25% and the charts could be i) Bar Chart on 'Entity Name' (25% width) ii) Scatterplot on Case Volume (50% width) iii) Pie chart with 'Case Type'.  The second row can be 60%-40% split with Geographic chart in the 60% width and the Heat-map in the 40% width.

3. For Pie-chart on 'Case Type', The Labels should be like "Case Type, <Selected Metric>, (% Selected Metric).  For example,  Defendant, 209mb, (20.3%) could be a label for one of the pie slice. 

4. For 'Bar-chart', The Labels on the right should be like 'Total Metric Value' & Percentage of that Metric Value in parenthesis. Like,  "Costumes-West                                            4,200 (68.2%)"

5. For the Scatter-plot, the bubbles should not overlap on the axis and should not be clipped either. You could use padding if required.  Also, bubble's opacity should be set to 0.6/0.7

6. For the heat-map, the Labels should be like: "Matter Type", "Total Metric Value" (% Metric Value).  both in separate lines.  Also, The label should only be displayed when the '% Metric Value' is greater than 10%. Otherwise, the label should not be displayed. 

7.  As a generic point, sort all the datasets in descending order (where ever you are generating summaries at the client side).  This will have all bar charts sorted and user doesn't have to spend time to figure-out what are the top 3 or 5 items to focus on.

8. Each chart should have it's own title on the top left (or some where appropriate based on the visualization).  

9.  All axis should have axis labels with appropriate number of tick marks so that there won't be any overlaps or clipped labels. 

10. These are mostly, aesthetic but most of these have to be implemented in D3 code and some of them can be in CSS.

**Comment by zeleniy** [comment]
@rrekapalli it seems everything done. Also it seems better to use legend for pie chart instead of labels. They are may overlap and i don't know how to fix that.

**Comment by rrekapalli** [comment]
Sure, not a problem. Should be fine to have legend than the labels for pie chart.  Legend could be shown at the bottom of the chart.  We are not expecting more than four categories for this pie chart. Hence, real estate should not be a problem. Use a little smaller font if required. 

A couple more points based on the latest dashboard:
1. Can we have at least 3px padding between the 'Tiles' at the top?
2. For the scatter plot, can we use 'Matter Type' colors for all case bubbles?  In the sense, each bubble should get the same color that is given to the matter type.
3.  Tooltips have not yet been implemented it seems. For the 'heat map', since we are not displaying labels for all the rectangles, tooltips would make sense. A tooltip of this sort would be appreciable (http://www.datasketch.es/january/code/nadieh/).
4. Can we switch Geographic map to the left on the second row of the charts with 60% width?  So, the Matter Type heat map would be moved to the right with 40% width.
5. 'Entity Name' & 'Case Types' charts width can be reduced a little bit more to make space for the scatter plot in the middle.  We are expecting about 30K cases for an year and that many bubbles could look clumsy in that little space.  So, A width of about 50% would be ideal.  
6. Can we have some 'transition' effects when we interact with charts by applying filters etc.? Currently, it's looking little abrupt and users might not be able to discern the changes.
7. 'Clear/Reset Filters' button should be there at the top beside the drop down controls.
8.  For the 'Case Type' pie chart, the labels (or Legends) should change based on the metric selected at the top.  For example, it should display count of cases when 'Count' radio button is selected; and SUM('DataSourcesSize') when 'Size' radio button is selected.
9. The 'height' of the timeline brush can be reduced a little bit.  Timeline filter not filtering out the cases in the 'scatter plot.
10.  When I wanted to print this dashboard, the heat map is not printing correctly.  The whole dashboard should be print ready. In the sense, when I take a print out (even when filters applied), it should print the current view with out any loss of details.
11. For the 'heat map', seems like 'count' & 'size' filters are not being reflected.  

Please feel free to let me know in case you have any further questions.

**Comment by rrekapalli** [comment]
Do you need any clarifications on this?

**Comment by zeleniy** [comment]
No, here everything is done
