### ISSUE TITLE
Tooltip content

### ISSUE THREAD

**Issue by zeleniy** [zeleniy/rDashboard#9]
@rrekapalli please describe what data tooltip should show for each chart.

**Comment by rrekapalli** [comment]
Hi Alex, 

Please find below the Titles and the Tooltip details for each chart in the dashboard.    Please do let me know if you have any concerns or questions. Sorry for the delay though!

**1. Entity Names (Bar Chart):**
Title: 		Entity-wise distribution (Left Aligned)
Sub Title: 	`<Not Required at the moment>`
Tool Tip:
Title:  `<Entity Name>`
```
    Matters:      <Matter Count of this entity>
    Cases:        <Case Count of this entity>
    Custodians:   <Custodian Count of all entities of all cases of this entity>
    Data Sources: <Data Sources of all Data Sources of cases of this entity>
    Total Size:   <Total Data Sources Size of all cases of this entity>
```
**2. Case Name (Scatterplot)**
Title:		Case Population (Center Aligned)
Sub Title:	Cases vs Data Sources plotted on Case Created Date
Tool Tip:
Title: `<Case Name> (Matter Name)`
```
  Law Firm:	     <Law Firm>
  Court Name:	     <Court Name>
  Custodian Count:   <Custodian Count>
  Data Source Count: <Data Source Count>
  Total Size:	     <Data Sources Size>
```
**3. Case Types (Pie Chart)**
Title:		Case Type Distribution
Sub Title:	<Not required at the moment>
Tool Tip:
Title:	`<Case Type>`
```
   Matters:  XX (% of Total Matters)
   Cases:    YY (% of Total Cases)
   Custodians:  AA
   Data Sources: BB
   Data Volume:  ZZZ GB (% of Total Size)
```
**4. Geographic Map:**
Title: 		`Location-wise <Data Source> Distribution`
Sub Title:  	`Geographic distribution of <Data Sources>`
Tool Tip: 
Title: `<Country Name>`
```
  Matters:  XX (% of Total Matters)
  Cases:    YY (% of Total Cases)
  Custodians:  AA
  Data Sources: BB
  Data Volume:  ZZZ GB (% of Total Size)
```
**5. Heat Map:**
Tital:	Matter Type Distribution
Tool Tip:
Title:  `<Matter Type>`
```
  Maters:   XX (% of Total Matters)
  Cases:    YY (% of Total Cases)
  Custodians: AA
  Data Sources:  BB
  Data Volume:  ZZZ GB (% of Total Size)
```

**Comment by rrekapalli** [comment]
Looks like there's some issue with the formatting!  But those are the details that should be there in the tool tip.

**Comment by rrekapalli** [comment]
Also, one more thing:  Can we take 'Collected Data Sources count' as the base number for all charts as the initial value?  Looks like currently 'PROCESSED' data sources count is being considered for all charts!  


![dashboardfeedback](https://user-images.githubusercontent.com/533433/31933231-2dd8a94c-b8c6-11e7-955a-718e921ff17e.png)

**Comment by rrekapalli** [comment]
By the way, printing issue is still not resolved, I think.

**Comment by zeleniy** [comment]
About `568` vs `567`. My calculations:
```
> x$ProcessedVolumesSize
  [1]  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  6.5  0.0  0.0 13.9  6.5  0.0 13.9  0.0 20.4  0.0 20.4  0.0  0.0  0.0 14.0  0.0  0.0  0.0
 [27]  0.0  0.0  0.0  0.0  0.0  0.0 14.0  0.0 14.0 20.5 14.0 20.4  0.0  0.0  0.0  0.0 94.7 14.0  0.0 20.5 21.2  0.0  0.0  0.3 20.5  0.0
 [53]  0.0  0.0  0.0  0.0  0.0 21.4  0.0  0.0  0.0  0.1  0.1 14.4 21.7  6.8  0.0  6.5  0.0 21.2  0.0  0.0 13.0  0.0 21.9  0.0  0.3  0.0
 [79]  6.5  0.5  0.5  0.0  0.0  0.0  0.0  0.0  6.8  0.0  0.0  0.0  0.0 27.9  0.0  0.0  0.3  0.0 24.2  0.0 24.2  0.0  0.3  0.0
> sum(x$ProcessedVolumesSize)
[1] 568.3
> round(sum(x$ProcessedVolumesSize))
[1] 568
```

**Comment by zeleniy** [comment]
> Also, one more thing: Can we take 'Collected Data Sources count' as the base number for all charts as the initial value? Looks like currently 'PROCESSED' data sources count is being considered for all charts!

By default all chart use `DataSourceCount` columns as value. If user click on `size` radio, all charts use `DataSourceSize`. If user click on any tile, value column become `ProcessedVolumesSize` (if `Processed ` tile and `size` radio are selected).

So questions is - do you want do select `PROCESSED` tile by default? Now no one tile selected by default on page loading.

**Comment by zeleniy** [comment]
About pie chart. Calculations:
```
> x$DataSourceCount
  [1]  6  4  3  7  0  4  2  9  9  6  8  6 18 12  6  6  6  4 15  8  2  0  3  0  0  0  0  3  3  2  4  6  6  6  2  4  4  2  2  2  2  2  9  4
 [45]  2  6  6  6  9 15 15  6  0  0  0  9  6 15  4  3  4  2  1  3  6  6  2  6 12  6  0  3  6  9 40  2  3  4 12 12  3  3  6  6  3  6  9  3
 [89]  9  9  9  6  0  5  6  3  6  6  6  6  3  6
> sum(x$DataSourceCount)
[1] 567
> 493 + 62 + 12
[1] 567
```
It seems they are correct.

**Comment by rrekapalli** [comment]
This calculation is correct when we are in the 'Size' mode, but the problem in the attached screenshot was it was in the 'Count' mode.  It should be displaying the Data Source counts, which should be integers!  Please let me know if I miss anything.

**Comment by rrekapalli** [comment]
Ah!  I think this is the problem with dummy data I provided.  The COLLECTED data source count should never be greater than the DataSourceCount - that's where I got confused!  I'll send out latest API data set so that we can test out the numbers and double check the calculations.

**Comment by rrekapalli** [comment]
Alex, seems like there's an issue with the mode!  Please see the attached screenshot.  I have selected 'COLLECTED' & in 'Count' mode, but the charts are displaying the stats from 'Size' mode!  

![mode issue](https://user-images.githubusercontent.com/533433/31942891-7b3827d0-b8e4-11e7-835c-8e5d6cb3b0c9.png)

**Comment by rrekapalli** [comment]
Here is the new sample data that can be used for testing, Alex.  This is from a better version of the application and not a random data set.  So, we should have more legible numbers and counts in this data set.  There might be some small changes in the columns names (should be very minimal) as we haven't made much changes in the API.  

[CaselevelStats.xlsx](https://github.com/zeleniy/rDashboard/files/1410851/CaselevelStats.xlsx)
